apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: go-mar7-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-mar7-1 
  name: go-mar7-1
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: go-mar7-1 
